# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

Answers for questions:
15, 19, 25, 35, 37, 42, 47, 50, 53, 58, 59, 64, 68, 69, 71, 75, 76, 84, 87, 89, 90, 96, 97, 100

In [1]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [10]:
def build_2d_array_1border_0inside(n=3):
    if n <1:
        print("invalid shape")
        return None
    elif n==1:
        return np.array([1])        
    # Start with zeros 2d array
    array = np.zeros((n,n))
    # fill borders with ones
    num_rows, num_cols = np.shape(array)
    for row in range(num_rows):
        array[row,0] = 1
        array[row,-1] = 1
    # fill first and last rows with ones
    array[0,:] = 1
    array[-1,:] = 1
    return array

print(build_2d_array_1border_0inside(n=5))




[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [15]:
def checkerboard(n=8):
    array = np.zeros((n,n))
    rows, cols = np.shape(array)
    for row in range(rows):
        if row % 2 == 0:
            # start with white
            ones_indices = [k for k in range(8) if k%2==1] 
            array[row,ones_indices] = 1
        else:
            #start with the black
            ones_indices = [k for k in range(8) if k%2==0] 
            array[row,ones_indices] = 1
    return array

print(checkerboard())



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [28]:
array = np.linspace(1,10, num=10)
def negate_between3_and8_inplace(array):
    array[(array<8) & (array>3)] = -array[(array<8) & (array>3)] 
    return array
negate_between3_and8_inplace(array)

array([ 1.,  2.,  3., -4., -5., -6., -7.,  8.,  9., 10.])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:
def compute_35(A,B):
    return (A+B)*(- A/2)



#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
array = np.zeros((5,5))
for row in range(np.shape(array)[0]):
    array[row,:] +=row
print(array)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [39]:
def check_equality(A,B):
    if np.shape(A) != np.shape(B):
        return False
    equal_indices = (A == B)
    if equal_indices.all():
        return True
    return False
A = np.ones((3,3))
B = np.zeros((3,3))
C = np.ones((3,3))
D = np.zeros((4,4))

print(check_equality(A,B))
print(check_equality(A,C))
print(check_equality(B,D))



False
True
False


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [43]:
def cauchy_matrix(X,Y):
    rows_X = len(X)
    cols_Y = len(Y)
    C = np.zeros((rows_X, cols_Y))
    for i in range(rows_X):
        for j in range(cols_Y):
            denominator = (X[i] - Y[j])
            if denominator == 0:
                C[i,j] = np.nan
            else:
                C[i,j]= 1 / (X[i] - Y[j])
    return C

X = np.linspace(1,5, num=5)
Y = np.linspace(3,7,num=5)
print(cauchy_matrix(X,Y))

[[-0.5        -0.33333333 -0.25       -0.2        -0.16666667]
 [-1.         -0.5        -0.33333333 -0.25       -0.2       ]
 [        nan -1.         -0.5        -0.33333333 -0.25      ]
 [ 1.                 nan -1.         -0.5        -0.33333333]
 [ 0.5         1.                 nan -1.         -0.5       ]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [47]:
v = np.linspace(1,10, num=10)
s = 6.6

def closest_val(vector, scalar):
    min_error = np.inf
    closest_value = np.nan
    for value in vector:
        error = np.abs(scalar - value)
        if error < min_error:
            closest_val = value
            min_error = error
    return closest_val

print(closest_val(v,s))




7.0


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [55]:
a = np.linspace(1,5,num=5, dtype = float)
a = a.astype(int)
print(a)



[1 2 3 4 5]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [61]:
def substract_row_mean(A):
    rows, col = np.shape(A)
    for row in range(rows):
        A[row,:] = A[row,:] / np.mean(A[row,:])
    return A

A = np.ones((3,3)) * 3
A[0][0] -=1
A[1][0] += 2
print(substract_row_mean(A))


[[0.75       1.125      1.125     ]
 [1.36363636 0.81818182 0.81818182]
 [1.         1.         1.        ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [67]:
# *Assuming the exercise meant 2D array
n = 1
A = np.array([[1,2,3], 
             [1,1,3],
             [1,5,0],
             [2,4,6]])
def sort_by_nth_col(A,n):
    nth_col = A[:,n]
    indices = np.argsort(nth_col)
    new_A = A.copy()
    rows, cols = np.shape(A)
    for row in range(rows):
        new_A[row] = A[indices[row]]
    return new_A

print(sort_by_nth_col(A,n))







[[1 1 3]
 [1 2 3]
 [2 4 6]
 [1 5 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [68]:
vector = np.array([0,1,2,3,4,5,6,7,8,9])
indices_vector = np.array([5,6,5,2,1])

def add_one_to_indiced_element(vector, indices_vector):
    # get unique values from indices vector
    unique_indices = np.unique(indices_vector)
    vector[indices_vector] = vector[indices_vector] + 1
    return vector

add_one_to_indiced_element(vector, indices_vector)

array([0, 2, 3, 3, 4, 6, 7, 7, 8, 9])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [73]:
D = np.array([1,2,3,4,5,6,7])
S =[[0,1,5],[2,3],[4,6]]
def excersize_68(D, S):
    means = []
    for subset in S:
        means.append(np.mean(D[subset]))
    return means

print(excersize_68(D,S))



[np.float64(3.0), np.float64(3.5), np.float64(6.0)]


#### 69. How to get the diagonal of a dot product? (★★★)

In [74]:
A= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

B= np.array([[9,8,7],
             [6,5,4],
             [3,2,1]])

np.diagonal(A*B)

array([ 9, 25,  9])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.random.rand(5,5,3)
B = np.random.rand(5,5)
# reshape B to fit As shape
a_depth = np.shape(A)[-1]
B = B[:, :, np.newaxis]
# concatanate B for a.depth times
B = np.tile(B, 3)
print(A*B)

[[[0.01857749 0.03139767 0.04046222]
  [0.2082759  0.30050532 0.41944244]
  [0.62116162 0.50687921 0.11447566]
  [0.06459238 0.2935578  0.36434258]
  [0.29241814 0.23868734 0.12989682]]

 [[0.03416083 0.03603942 0.02744053]
  [0.74670804 0.18706882 0.71794412]
  [0.09308193 0.18706344 0.12438605]
  [0.54714534 0.18702848 0.26022261]
  [0.22285911 0.16564085 0.03488937]]

 [[0.0159361  0.14185024 0.18333474]
  [0.63550855 0.46839391 0.75376839]
  [0.25791194 0.13526117 0.47931596]
  [0.03895392 0.38811302 0.12244611]
  [0.11220995 0.25661428 0.37340788]]

 [[0.322499   0.48362868 0.28979086]
  [0.50959065 0.26739231 0.24019457]
  [0.04408269 0.03032901 0.00355591]
  [0.02643973 0.01990556 0.01174944]
  [0.5043608  0.06069431 0.39519418]]

 [[0.33649461 0.23121975 0.32015133]
  [0.28688537 0.09436731 0.08624272]
  [0.13307822 0.17924337 0.09100602]
  [0.30867742 0.25889433 0.00576805]
  [0.69651378 0.25916611 0.6476423 ]]]


#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
Z = np.array([1,2,3, 4,5,6,7,8,9])

def exce_76(Z):
    n = len(Z) - 2
    A = np.zeros((n,3))
    for i in range(n):
        A[i] = Z[i:i+3]
    return A
print(exce_76(Z))


[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]
 [5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [90]:
A = np.random.rand(10,10)
rows, cols = np.shape(A)
n = 3
blocks = []
for i in range(rows):
    for j in range(cols):
        if i+2 < rows and j+2 < cols:
            blocks.append(A[i:i+3, j:j+3])
print(blocks)
print(len(blocks))


[array([[0.0774281 , 0.91258753, 0.87779565],
       [0.80965676, 0.41714151, 0.09993891],
       [0.05335887, 0.60939905, 0.89651282]]), array([[0.91258753, 0.87779565, 0.14141533],
       [0.41714151, 0.09993891, 0.94778563],
       [0.60939905, 0.89651282, 0.72412171]]), array([[0.87779565, 0.14141533, 0.55516018],
       [0.09993891, 0.94778563, 0.32447377],
       [0.89651282, 0.72412171, 0.5034454 ]]), array([[0.14141533, 0.55516018, 0.50650476],
       [0.94778563, 0.32447377, 0.94398696],
       [0.72412171, 0.5034454 , 0.24631132]]), array([[0.55516018, 0.50650476, 0.57239469],
       [0.32447377, 0.94398696, 0.43233331],
       [0.5034454 , 0.24631132, 0.06229978]]), array([[0.50650476, 0.57239469, 0.75755689],
       [0.94398696, 0.43233331, 0.42578925],
       [0.24631132, 0.06229978, 0.53519764]]), array([[0.57239469, 0.75755689, 0.22517276],
       [0.43233331, 0.42578925, 0.99663653],
       [0.06229978, 0.53519764, 0.95068136]]), array([[0.75755689, 0.22517276, 0.483891

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [93]:
A = np.random.rand(16,16)
rows, cols = np.shape(A)
n = 4
block_sums = []
for i in range(0,rows,n):
    for j in range(0,cols,n):
        if i+n-1 < rows and j+n-1 < cols:
            block_sums.append(np.sum(A[i:i+n-1, j:j+n-1]))
print(block_sums)
len(block_sums)

[np.float64(4.123437161499012), np.float64(4.7725361198322265), np.float64(3.86082008036085), np.float64(4.6593716994910155), np.float64(2.88990016769294), np.float64(3.406885112491349), np.float64(5.435141126662678), np.float64(6.217466606772987), np.float64(5.584312841971486), np.float64(4.207198922687504), np.float64(5.111701350784927), np.float64(3.7345189337373936), np.float64(5.198580437109104), np.float64(3.80218455304747), np.float64(4.208835307687874), np.float64(3.8660368586089042)]


16

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [95]:
array = np.array([1,2,2,5,6,9,2,3,3])
n = 3
print(np.sort(array)[-n:])

[5 6 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [ ]:
vectors = np.array([[1,2,3], [4,5,6], [7,8,9]])
num_vecs, vec_length = np.shape(vectors)
result = []
# get cartesian product
for i in  range(num_vecs):
    for j in range(vec_length):
        

    



#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [101]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [1,2,3],
                  [4,5,6]])
unique_rows = []
for row in array:
    in_unique = False
    for unique_row in unique_rows:
        # print(unique_row)
        # print(row)
        equality = (unique_row == row)
        if equality.all():
            in_unique = True
    if not in_unique:
        unique_rows.append(row)


print(unique_rows)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)