# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

Answers for questions:
15, 19, 25, 35, 37, 42, 47, 50, 53, 58, 59, 64, 68, 69, 71, 75, 76, 84, 87, 89, 90, 96, 97, 100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [4]:
def build_2d_array_1border_0inside(n=3):
    if n <1:
        print("invalid shape")
        return None
    elif n==1:
        return np.array([1])        
    # Start with zeros 2d array
    array = np.zeros((n,n))
    # fill borders with ones
    num_rows, num_cols = np.shape(array)
    for row in range(num_rows):
        array[row,0] = 1
        array[row,-1] = 1
    # fill first and last rows with ones
    array[0,:] = 1
    array[-1,:] = 1
    return array

print(build_2d_array_1border_0inside(n=5))




[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [5]:
def checkerboard(n=8):
    array = np.zeros((n,n))
    rows, cols = np.shape(array)
    for row in range(rows):
        if row % 2 == 0:
            # start with white
            ones_indices = [k for k in range(8) if k%2==1] 
            array[row,ones_indices] = 1
        else:
            #start with the black
            ones_indices = [k for k in range(8) if k%2==0] 
            array[row,ones_indices] = 1
    return array

print(checkerboard())



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [6]:
array = np.linspace(1,10, num=10)
def negate_between3_and8_inplace(array):
    array[(array<8) & (array>3)] = -array[(array<8) & (array>3)] 
    return array
negate_between3_and8_inplace(array)

array([ 1.,  2.,  3., -4., -5., -6., -7.,  8.,  9., 10.])

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
def compute_35(A,B):
    return (A+B)*(- A/2)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
array = np.zeros((5,5))
for row in range(np.shape(array)[0]):
    array[row,:] +=row
print(array)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [9]:
def check_equality(A,B):
    if np.shape(A) != np.shape(B):
        return False
    equal_indices = (A == B)
    if equal_indices.all():
        return True
    return False
A = np.ones((3,3))
B = np.zeros((3,3))
C = np.ones((3,3))
D = np.zeros((4,4))

print(check_equality(A,B))
print(check_equality(A,C))
print(check_equality(B,D))



False
True
False


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [10]:
def cauchy_matrix(X,Y):
    rows_X = len(X)
    cols_Y = len(Y)
    C = np.zeros((rows_X, cols_Y))
    for i in range(rows_X):
        for j in range(cols_Y):
            denominator = (X[i] - Y[j])
            if denominator == 0:
                C[i,j] = np.nan
            else:
                C[i,j]= 1 / (X[i] - Y[j])
    return C

X = np.linspace(1,5, num=5)
Y = np.linspace(3,7,num=5)
print(cauchy_matrix(X,Y))

[[-0.5        -0.33333333 -0.25       -0.2        -0.16666667]
 [-1.         -0.5        -0.33333333 -0.25       -0.2       ]
 [        nan -1.         -0.5        -0.33333333 -0.25      ]
 [ 1.                 nan -1.         -0.5        -0.33333333]
 [ 0.5         1.                 nan -1.         -0.5       ]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [11]:
v = np.linspace(1,10, num=10)
s = 6.6

def closest_val(vector, scalar):
    min_error = np.inf
    closest_value = np.nan
    for value in vector:
        error = np.abs(scalar - value)
        if error < min_error:
            closest_val = value
            min_error = error
    return closest_val

print(closest_val(v,s))




7.0


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
a = np.linspace(1,5,num=5, dtype = float)
a = a.astype(int)
print(a)

[1 2 3 4 5]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [13]:
def substract_row_mean(A):
    rows, col = np.shape(A)
    for row in range(rows):
        A[row,:] = A[row,:] / np.mean(A[row,:])
    return A

A = np.ones((3,3)) * 3
A[0][0] -=1
A[1][0] += 2
print(substract_row_mean(A))


[[0.75       1.125      1.125     ]
 [1.36363636 0.81818182 0.81818182]
 [1.         1.         1.        ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
# *Assuming the exercise meant 2D array
n = 1
A = np.array([[1,2,3], 
             [1,1,3],
             [1,5,0],
             [2,4,6]])
def sort_by_nth_col(A,n):
    nth_col = A[:,n]
    indices = np.argsort(nth_col)
    new_A = A.copy()
    rows, cols = np.shape(A)
    for row in range(rows):
        new_A[row] = A[indices[row]]
    return new_A

print(sort_by_nth_col(A,n))


[[1 1 3]
 [1 2 3]
 [2 4 6]
 [1 5 0]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [15]:
vector = np.array([0,1,2,3,4,5,6,7,8,9])
indices_vector = np.array([5,6,5,2,1])

def add_one_to_indiced_element(vector, indices_vector):
    # get unique values from indices vector
    unique_indices = np.unique(indices_vector)
    vector[indices_vector] = vector[indices_vector] + 1
    return vector

add_one_to_indiced_element(vector, indices_vector)

array([0, 2, 3, 3, 4, 6, 7, 7, 8, 9])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [16]:
D = np.array([1,2,3,4,5,6,7])
S =[[0,1,5],[2,3],[4,6]]
def excersize_68(D, S):
    means = []
    for subset in S:
        means.append(np.mean(D[subset]))
    return means

print(excersize_68(D,S))



[np.float64(3.0), np.float64(3.5), np.float64(6.0)]


#### 69. How to get the diagonal of a dot product? (★★★)

In [17]:
A= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

B= np.array([[9,8,7],
             [6,5,4],
             [3,2,1]])

np.diagonal(A*B)

array([ 9, 25,  9])

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [18]:
A = np.random.rand(5,5,3)
B = np.random.rand(5,5)
# reshape B to fit As shape
a_depth = np.shape(A)[-1]
B = B[:, :, np.newaxis]
# concatanate B for a.depth times
B = np.tile(B, 3)
print(A*B)

[[[0.38206022 0.06876815 0.25087244]
  [0.07408116 0.10072679 0.21116424]
  [0.39485815 0.27531104 0.63027362]
  [0.83127282 0.53078707 0.09188615]
  [0.42748812 0.51331844 0.00812899]]

 [[0.35062909 0.36743142 0.25497434]
  [0.05629511 0.07730051 0.16355636]
  [0.02733601 0.85703922 0.50336289]
  [0.43563292 0.6039284  0.22592554]
  [0.02889698 0.05506446 0.02854885]]

 [[0.14502924 0.14415605 0.0893784 ]
  [0.32650669 0.14347107 0.18181049]
  [0.92366925 0.87410022 0.06946653]
  [0.22821977 0.14920135 0.09719646]
  [0.00548421 0.2075107  0.01351839]]

 [[0.59364571 0.358945   0.31952135]
  [0.04449868 0.09224671 0.11330758]
  [0.30458809 0.30188245 0.67036078]
  [0.0175895  0.02529912 0.00308186]
  [0.46948358 0.28935423 0.33319241]]

 [[0.29141587 0.27508665 0.38680862]
  [0.02648754 0.19671243 0.24820334]
  [0.30702157 0.69311654 0.27071387]
  [0.01400479 0.01005316 0.06211848]
  [0.01148248 0.054635   0.06220536]]]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [19]:
Z = np.array([1,2,3, 4,5,6,7,8,9])

def exce_76(Z):
    n = len(Z) - 2
    A = np.zeros((n,3))
    for i in range(n):
        A[i] = Z[i:i+3]
    return A
print(exce_76(Z))


[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]
 [5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [20]:
A = np.random.rand(10,10)
rows, cols = np.shape(A)
n = 3
blocks = []
for i in range(rows):
    for j in range(cols):
        if i+2 < rows and j+2 < cols:
            blocks.append(A[i:i+3, j:j+3])
print(blocks)
print(len(blocks))


[array([[0.54683855, 0.42162051, 0.8789874 ],
       [0.97257447, 0.89579584, 0.73830351],
       [0.6740285 , 0.51439832, 0.23290849]]), array([[0.42162051, 0.8789874 , 0.24205714],
       [0.89579584, 0.73830351, 0.04017856],
       [0.51439832, 0.23290849, 0.87785394]]), array([[0.8789874 , 0.24205714, 0.11690367],
       [0.73830351, 0.04017856, 0.62708636],
       [0.23290849, 0.87785394, 0.90307838]]), array([[0.24205714, 0.11690367, 0.57325596],
       [0.04017856, 0.62708636, 0.78093233],
       [0.87785394, 0.90307838, 0.62576938]]), array([[0.11690367, 0.57325596, 0.91273384],
       [0.62708636, 0.78093233, 0.68893653],
       [0.90307838, 0.62576938, 0.95960822]]), array([[0.57325596, 0.91273384, 0.00203784],
       [0.78093233, 0.68893653, 0.7122079 ],
       [0.62576938, 0.95960822, 0.98197363]]), array([[0.91273384, 0.00203784, 0.46824204],
       [0.68893653, 0.7122079 , 0.05243979],
       [0.95960822, 0.98197363, 0.89756543]]), array([[0.00203784, 0.46824204, 0.838851

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [21]:
A = np.random.rand(16,16)
rows, cols = np.shape(A)
n = 4
block_sums = []
for i in range(0,rows,n):
    for j in range(0,cols,n):
        if i+n-1 < rows and j+n-1 < cols:
            block_sums.append(np.sum(A[i:i+n-1, j:j+n-1]))
print(block_sums)
len(block_sums)

[np.float64(3.9565962863474127), np.float64(6.837074341629074), np.float64(4.387136682830936), np.float64(4.689084415415294), np.float64(6.128347064651694), np.float64(5.156690958697472), np.float64(3.7677627685689905), np.float64(5.545602695916967), np.float64(6.109917652134804), np.float64(3.6888270256715026), np.float64(3.1053178607099756), np.float64(5.239044109481616), np.float64(4.691691431384719), np.float64(4.470424987936287), np.float64(4.090620026086221), np.float64(5.166337042201326)]


16

#### 89. How to get the n largest values of an array (★★★)

In [22]:
array = np.array([1,2,2,5,6,9,2,3,3])
n = 3
print(np.sort(array)[-n:])

[5 6 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [40]:
vectors = np.array([[1,2,3], [4,5,6], [7,8,9]])
num_vecs, vec_length = np.shape(vectors)
grids = np.meshgrid(*vectors)
cartesian_product = np.column_stack([grid.flatten() for grid in grids])
print(cartesian_product)

[[1 4 7]
 [1 4 8]
 [1 4 9]
 [2 4 7]
 [2 4 8]
 [2 4 9]
 [3 4 7]
 [3 4 8]
 [3 4 9]
 [1 5 7]
 [1 5 8]
 [1 5 9]
 [2 5 7]
 [2 5 8]
 [2 5 9]
 [3 5 7]
 [3 5 8]
 [3 5 9]
 [1 6 7]
 [1 6 8]
 [1 6 9]
 [2 6 7]
 [2 6 8]
 [2 6 9]
 [3 6 7]
 [3 6 8]
 [3 6 9]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [1,2,3],
                  [4,5,6]])
unique_rows = []
for row in array:
    in_unique = False
    for unique_row in unique_rows:
        # print(unique_row)
        # print(row)
        equality = (unique_row == row)
        if equality.all():
            in_unique = True
    if not in_unique:
        unique_rows.append(row)


print(unique_rows)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [26]:
A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)

np.einsum('i,i', A, B)    # inner
np.einsum('i,j->ij', A, B)    # outer
np.einsum('i->', A)       # sum
np.einsum('i,i->i', A, B) # mul

array([0.23270416, 0.19746529, 0.46994289, 0.22430726, 0.02691932])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [24]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12091158  0.22676235]
